# Generated by Django 4.2.1 on 2023-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='time_period',
            field=models.IntegerField(choices=[(3600, '1 Hour'), (7200, '2 Hours'), (10800, '3 Hours'), (21600, '6 Hours')], default=0),
        ),
    ]
