# Generated by Django 4.2 on 2023-05-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='weather_data',
        ),
    ]
