# Generated by Django 4.2 on 2023-04-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
    ]
