# Generated by Django 4.2.1 on 2023-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subscription_weather_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='time_period',
            field=models.IntegerField(choices=[(1, 'One'), (3, 'Three'), (6, 'Six'), (12, 'Twelve')], default=0),
        ),
    ]
