# Generated by Django 4.2 on 2023-04-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_options_alter_subscription_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='weather_data',
            new_name='_weather_data',
        ),
    ]
