# Generated by Django 4.2 on 2023-04-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='time_period',
            field=models.IntegerField(choices=[(4, 'Four'), (8, 'Eight'), (12, 'Twelve')], default=0),
        ),
    ]
