# Generated by Django 4.2.1 on 2023-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subscription_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
