# Generated by Django 4.2.1 on 2023-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subscription_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
