# Generated by Django 4.2 on 2023-04-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_weather_data_city__weather_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='_weather_data',
            new_name='weather_data',
        ),
    ]
