
version: '3.11'


services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn dwr.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    volumes: 
      - .:/usr/src/app
